"""customer accounts with password login, order delivery snapshot

Revision ID: 30327061b231
Revises: 7b8f34983d26
Create Date: 2026-08-13 10:05:09.082352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30327061b231'
down_revision: Union[str, None] = '7b8f34983d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.drop_index('ix_customers_mobile')
        batch_op.create_index(batch_op.f('ix_customers_mobile'), ['mobile'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('delivery_mobile', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('delivery_state', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('delivery_pincode', sa.String(length=12), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_pincode')
        batch_op.drop_column('delivery_state')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_mobile')
        batch_op.drop_column('delivery_name')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_mobile'))
        batch_op.create_index('ix_customers_mobile', ['mobile'], unique=False)
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
