"""add razorpay fields and stock_restored to orders

Revision ID: 7b8f34983d26
Revises: 202fea486840
Create Date: 2026-08-13 09:37:37.771835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8f34983d26'
down_revision: Union[str, None] = '202fea486840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=80), nullable=True))
        batch_op.add_column(
            sa.Column('stock_restored', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_orders_razorpay_order_id'), ['razorpay_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_razorpay_order_id'))
        batch_op.drop_column('stock_restored')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')

    # ### end Alembic commands ###
