"""add composite index on products active, deleted_at

Revision ID: 9f9717c254dc
Revises: 9fb186ac397e
Create Date: 2026-08-15 08:41:55.218587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9717c254dc'
down_revision: Union[str, None] = '9fb186ac397e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only the new composite index — the autogenerated drop/recreate of
    # ix_products_sku was a false positive (that index was created by an
    # earlier migration directly rather than declared on the model, so
    # autogenerate mistook it for something to remove). Leave it alone.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_active_deleted', ['active', 'deleted_at'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_active_deleted')
