"""add gift wrap and gift message to orders

Revision ID: 9fb3f61ed2f6
Revises: b2092b6ee490
Create Date: 2026-08-14 22:24:06.228019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb3f61ed2f6'
down_revision: Union[str, None] = 'b2092b6ee490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_wrap', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('gift_message', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('gift_message')
        batch_op.drop_column('gift_wrap')

    # ### end Alembic commands ###
