"""add gift options, order gift options, order gift_charges

Revision ID: a863cb2dc1ce
Revises: 9f9717c254dc
Create Date: 2026-08-15 09:40:32.960574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a863cb2dc1ce'
down_revision: Union[str, None] = '9f9717c254dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_gift_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=80), nullable=False),
    sa.Column('price_snapshot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_gift_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_gift_options_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_charges', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

    # Seed two starter options so the checkout section isn't empty on first
    # deploy — the admin can edit/add/remove from /admin/gift-options.
    op.execute(
        "INSERT INTO gift_options (name, price, active, sort_order, created_at) VALUES "
        "('Gift Wrap', 50, true, 0, now()), "
        "('Greeting Card', 30, true, 1, now())"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('gift_charges')

    with op.batch_alter_table('order_gift_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_gift_options_order_id'))

    op.drop_table('order_gift_options')
    op.drop_table('gift_options')
    # ### end Alembic commands ###
