"""add product and order item personalization fields

Revision ID: a903b6eda497
Revises: 400f37effd4e
Create Date: 2026-08-18 01:51:32.381351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a903b6eda497'
down_revision: Union[str, None] = '400f37effd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personalization_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('personalization_message', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('personalization_date', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('personalization_photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personalize_name', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('personalize_message', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('personalize_date', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('personalize_photo', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('personalize_photo')
        batch_op.drop_column('personalize_date')
        batch_op.drop_column('personalize_message')
        batch_op.drop_column('personalize_name')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('personalization_photo_url')
        batch_op.drop_column('personalization_date')
        batch_op.drop_column('personalization_message')
        batch_op.drop_column('personalization_name')

    # ### end Alembic commands ###
