"""remove razorpay columns, cash on delivery only

Revision ID: b2092b6ee490
Revises: 30327061b231
Create Date: 2026-08-13 10:16:57.123080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2092b6ee490'
down_revision: Union[str, None] = '30327061b231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_razorpay_order_id')
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('razorpay_payment_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', sa.VARCHAR(length=80), nullable=True))
        batch_op.create_index('ix_orders_razorpay_order_id', ['razorpay_order_id'], unique=False)

    # ### end Alembic commands ###
