"""add product_events table for lightweight analytics

Revision ID: bd47b98236b3
Revises: a4be5502a30a
Create Date: 2026-08-15 10:10:12.915820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd47b98236b3'
down_revision: Union[str, None] = 'a4be5502a30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_events_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_events_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_product_events_created_at'))

    op.drop_table('product_events')
    # ### end Alembic commands ###
