"""add seo meta fields, review photos, gift combos, notify me, abandoned cart

Revision ID: c2e9cbdcaf14
Revises: 338380d4c331
Create Date: 2026-08-18 02:33:27.978332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e9cbdcaf14'
down_revision: Union[str, None] = '338380d4c331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bundle_price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_bundles_slug'), ['slug'], unique=True)

    op.create_table('abandoned_cart_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('cart_summary', sa.Text(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abandoned_cart_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abandoned_cart_leads_customer_id'), ['customer_id'], unique=True)

    op.create_table('product_bundle_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['product_bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_bundle_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_bundle_items_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_bundle_items_product_id'), ['product_id'], unique=False)

    op.create_table('stock_notify_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'customer_id', name='uq_notify_product_customer')
    )
    with op.batch_alter_table('stock_notify_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_notify_requests_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_notify_requests_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')

    with op.batch_alter_table('stock_notify_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_notify_requests_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_notify_requests_customer_id'))

    op.drop_table('stock_notify_requests')
    with op.batch_alter_table('product_bundle_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_bundle_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_bundle_items_bundle_id'))

    op.drop_table('product_bundle_items')
    with op.batch_alter_table('abandoned_cart_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abandoned_cart_leads_customer_id'))

    op.drop_table('abandoned_cart_leads')
    with op.batch_alter_table('product_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_bundles_slug'))

    op.drop_table('product_bundles')
    # ### end Alembic commands ###
